transforms:
  - include: jvm.classes.loaded
    match_type: strict
    action: update
    new_name: jvm_classes_loaded


  - include: jvm.memory.heap.used
    match_type: strict
    action: update
    new_name: jvm_memory_bytes_used
    operations:
      - action: add_label
        new_label: area
        new_value: "heap"

  - include: jvm.memory.nonheap.used
    match_type: strict
    action: update
    new_name: jvm_memory_bytes_used
    operations:
      - action: add_label
        new_label: area
        new_value: "nonheap"

  - include: jvm.memory.pool.used
    match_type: strict
    action: update
    new_name: jvm_memory_pool_bytes_used
    operations:
      - action: update_label
        label: name
        new_label: pool

  - include: jvm.system.swap.space.total
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_totalswapspacesize


  - include: jvm.system.cpu.utilization
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_systemcpuload

  - include: jvm.cpu.recent_utilization
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_processcpuload


  - include: jvm.system.swap.space.free
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_freeswapspacesize


  - include: jvm.system.physical.memory.total
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_totalphysicalmemorysize


  - include: jvm.system.physical.memory.free
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_freephysicalmemorysize


  - include: jvm.open_file_descriptor.count
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_openfiledescriptorcount


  - include: jvm.system.available.processors
    match_type: strict
    action: update
    new_name: java_lang_operatingsystem_availableprocessors


  - include: jvm.threads.count
    match_type: strict
    action: update
    new_name: jvm_threads_current


  - include: jvm.threads.daemon
    match_type: strict
    action: update
    new_name: jvm_threads_daemon


  - include: tomcat.sessions
    match_type: strict
    action: update
    new_name: catalina_manager_activesessions


  - include: tomcat.rejected_sessions
    match_type: strict
    action: update
    new_name: catalina_manager_rejectedsessions


  - include: tomcat.traffic.received
    match_type: strict
    action: update
    new_name: catalina_globalrequestprocessor_bytesreceived


  - include: tomcat.traffic.sent
    match_type: strict
    action: update
    new_name: catalina_globalrequestprocessor_bytessent

  - include: tomcat.request_count
    match_type: strict
    action: update
    new_name: catalina_globalrequestprocessor_requestcount


  - include: tomcat.errors
    match_type: strict
    action: update
    new_name: catalina_globalrequestprocessor_errorcount


  - include: tomcat.processing_time
    match_type: strict
    action: update
    new_name: catalina_globalrequestprocessor_processingtime

