apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
      "agent": {
        "omit_hostname": true
      },
      "metrics": {
        "metrics_collected": {
          "statsd": {
            "service_address":":8125"
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: cwagentstatsdconfig
  namespace: amazon-cloudwatch