exporters:
    cloudwatch: {}
processors: {}
receivers:
    socket_listener: {}
service:
    pipelines:
        metrics:
            exporters:
                - cloudwatch
            processors: []
            receivers:
                - socket_listener
