connectors: {}
exporters:
  awscloudwatchlogs/emf_logs:
    certificate_file_path: ""
    emf_only: true
    endpoint: "https://fake_endpoint"
    imds_retries: 0
    local_mode: false
    log_group_name: emf/logs/default
    log_retention: 0
    log_stream_name: host_name_from_env
    max_retries: 2
    no_verify_ssl: false
    num_workers: 8
    proxy_address: ""
    raw_log: true
    region: us-east-1
    request_timeout_seconds: 30
    resource_arn: ""
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 5m0s
      max_interval: 30s
      multiplier: 1.5
      randomization_factor: 0.5
    role_arn: ""
    sending_queue:
      queue_size: 1000
    profile: ""
    shared_credentials_file: [ ]
  awsemf/containerinsights:
    certificate_file_path: ""
    detailed_metrics: false
    dimension_rollup_option: NoDimensionRollup
    disable_metric_extraction: false
    eks_fargate_container_insights_enabled: false
    endpoint: "https://fake_endpoint"
    imds_retries: 0
    enhanced_container_insights: true
    local_mode: false
    log_group_name: /aws/containerinsights/{ClusterName}/performance
    log_retention: 0
    log_stream_name: '{NodeName}'
    max_retries: 2
    metric_declarations:
      # container metrics
      - dimensions: [ [ ClusterName ], [ ClusterName, ContainerName, FullPodName, Namespace, PodName ], [ ClusterName, ContainerName, Namespace, PodName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - container_cpu_utilization
          - container_cpu_utilization_over_container_limit
          - container_memory_utilization
          - container_memory_utilization_over_container_limit
          - container_memory_failures_total
          - container_memory_limit
          - container_memory_request
          - container_filesystem_usage
          - container_filesystem_available
          - container_filesystem_utilization
          - container_status_running
          - container_status_terminated
          - container_status_waiting
          - container_status_waiting_reason_crash_loop_back_off
          - container_status_waiting_reason_image_pull_error
          - container_status_waiting_reason_start_error
          - container_status_waiting_reason_create_container_error
          - container_status_waiting_reason_create_container_config_error
          - container_status_terminated_reason_oom_killed
      # pod metrics
      - dimensions: [ [ ClusterName, Namespace, PodName ], [ ClusterName ], [ ClusterName, Namespace, Service ], [ ClusterName, Namespace ], [ ClusterName, FullPodName, Namespace, PodName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - pod_cpu_utilization
          - pod_memory_utilization
          - pod_network_rx_bytes
          - pod_network_tx_bytes
          - pod_cpu_utilization_over_pod_limit
          - pod_memory_utilization_over_pod_limit
      - dimensions: [ [ ClusterName, FullPodName, Namespace, PodName ], [ ClusterName, Namespace, PodName ], [ ClusterName, Namespace,  Service ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - pod_interface_network_rx_dropped
          - pod_interface_network_tx_dropped
      - dimensions: [ [ ClusterName, Namespace, PodName ], [ ClusterName ], [ ClusterName, FullPodName, Namespace, PodName ], [ ClusterName, Namespace, Service ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - pod_cpu_reserved_capacity
          - pod_memory_reserved_capacity
          - pod_number_of_container_restarts
          - pod_number_of_containers
          - pod_number_of_running_containers
          - pod_status_ready
          - pod_status_scheduled
          - pod_status_running
          - pod_status_pending
          - pod_status_failed
          - pod_status_unknown
          - pod_status_succeeded
          - pod_memory_request
          - pod_memory_limit
      # node metrics
      - dimensions: [ [ ClusterName, InstanceId, NodeName ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - node_cpu_utilization
          - node_memory_utilization
          - node_network_total_bytes
          - node_cpu_reserved_capacity
          - node_memory_reserved_capacity
          - node_number_of_running_pods
          - node_number_of_running_containers
          - node_cpu_usage_total
          - node_cpu_limit
          - node_memory_working_set
          - node_memory_limit
          - node_status_condition_ready
          - node_status_condition_disk_pressure
          - node_status_condition_memory_pressure
          - node_status_condition_pid_pressure
          - node_status_condition_network_unavailable
          - node_status_condition_unknown
          - node_status_capacity_pods
          - node_status_allocatable_pods
      - dimensions: [ [ ClusterName, InstanceId, NodeName ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - node_interface_network_rx_dropped
          - node_interface_network_tx_dropped
          - node_diskio_io_service_bytes_total
          - node_diskio_io_serviced_total
      # node fs metrics
      - dimensions: [ [ ClusterName, InstanceId, NodeName ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - node_filesystem_utilization
          - node_filesystem_inodes
          - node_filesystem_inodes_free
      # service metrics
      - dimensions: [ [ ClusterName, Namespace, Service ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - service_number_of_running_pods
      # deployment/stateful set/replica set metrics
      - dimensions: [ [ ClusterName, Namespace, PodName ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - replicas_desired
          - replicas_ready
          - status_replicas_available
          - status_replicas_unavailable
      # daemon set metrics
      - dimensions: [ [ ClusterName, Namespace, PodName ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - daemonset_status_number_available
          - daemonset_status_number_unavailable
      # namespace metrics
      - dimensions: [ [ ClusterName, Namespace ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - namespace_number_of_running_pods
      # cluster metrics
      - dimensions: [ [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - cluster_node_count
          - cluster_failed_node_count
          - cluster_number_of_running_pods
      # control plane metrics
      - dimensions: [ [ ClusterName, endpoint ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_storage_size_bytes
          - apiserver_storage_size_bytes
          - etcd_db_total_size_in_bytes
          - etcd_request_duration_seconds
      - dimensions: [ [ ClusterName, resource ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_storage_list_duration_seconds
          - apiserver_longrunning_requests
          - apiserver_storage_objects
      - dimensions: [ [ ClusterName, verb ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_request_duration_seconds
          - rest_client_request_duration_seconds
      - dimensions: [ [ ClusterName, code, verb ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_request_total
          - apiserver_request_total_5xx
      - dimensions: [ [ ClusterName, operation ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_admission_controller_admission_duration_seconds
          - apiserver_admission_step_admission_duration_seconds
          - etcd_request_duration_seconds
      - dimensions: [ [ ClusterName, code, method ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - rest_client_requests_total
      - dimensions: [ [ ClusterName, request_kind ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_current_inflight_requests
      - dimensions: [ [ ClusterName, name ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_admission_webhook_admission_duration_seconds
      - dimensions: [ [ ClusterName, group ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_requested_deprecated_apis
      - dimensions: [ [ ClusterName, reason ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_flowcontrol_rejected_requests_total
      - dimensions: [ [ ClusterName, priority_level ], [ ClusterName ] ]
        label_matchers: [ ]
        metric_name_selectors:
          - apiserver_flowcontrol_request_concurrency_limit
    metric_descriptors:
      - metric_name: apiserver_admission_controller_admission_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: apiserver_admission_step_admission_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: apiserver_admission_webhook_admission_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: apiserver_current_inflight_requests
        unit: Count
        overwrite: true
      - metric_name: apiserver_current_inqueue_requests
        unit: Count
        overwrite: true
      - metric_name: apiserver_flowcontrol_rejected_requests_total
        unit: Count
        overwrite: true
      - metric_name: apiserver_flowcontrol_request_concurrency_limit
        unit: Count
        overwrite: true
      - metric_name: apiserver_longrunning_requests
        unit: Count
        overwrite: true
      - metric_name: apiserver_request_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: apiserver_request_total
        unit: Count
        overwrite: true
      - metric_name: apiserver_request_total_5xx
        unit: Count
        overwrite: true
      - metric_name: apiserver_storage_objects
        unit: Count
        overwrite: true
      - metric_name: etcd_request_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: apiserver_storage_list_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: apiserver_storage_objects
        unit: Count
        overwrite: true
      - metric_name: apiserver_storage_db_total_size_in_bytes
        unit: Bytes
        overwrite: true
      - metric_name: apiserver_storage_size_bytes
        unit: Bytes
        overwrite: true
      - metric_name: etcd_db_total_size_in_bytes
        unit: Bytes
        overwrite: true
      - metric_name: etcd_request_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: rest_client_request_duration_seconds
        unit: Seconds
        overwrite: true
      - metric_name: rest_client_requests_total
        unit: Count
        overwrite: true
    namespace: ContainerInsights
    no_verify_ssl: false
    num_workers: 8
    output_destination: cloudwatch
    parse_json_encoded_attr_values:
      - Sources
      - kubernetes
    proxy_address: ""
    region: us-east-1
    request_timeout_seconds: 30
    resource_arn: ""
    resource_to_telemetry_conversion:
      enabled: true
    retain_initial_value_of_delta_metric: false
    role_arn: ""
    profile: ""
    shared_credentials_file: [ ]
    version: "0"
extensions: {}
processors:
  metricstransform/containerinsights:
    transforms:
      - include: apiserver_request_total
        match_type: regexp
        experimental_match_labels: { "code": "^5.*" }
        action: insert
        new_name: apiserver_request_total_5xx
        aggregation_type: ""
        group_resource_labels: { }
        operations: [ ]
        submatch_case: ""
  batch/containerinsights:
    metadata_cardinality_limit: 1000
    metadata_keys: []
    send_batch_max_size: 0
    send_batch_size: 8192
    timeout: 5s
  batch/emf_logs:
    metadata_cardinality_limit: 1000
    metadata_keys: []
    send_batch_max_size: 0
    send_batch_size: 8192
    timeout: 5s
receivers:
  awscontainerinsightreceiver:
    certificate_file_path: ""
    add_container_name_metric_label: true
    add_full_pod_name_metric_label: true
    add_service_as_attribute: true
    cluster_name: TestCluster
    collection_interval: 30s
    container_orchestrator: eks
    enable_control_plane_metrics: true
    endpoint: ""
    imds_retries: 0
    leader_lock_name: cwagent-clusterleader
    leader_lock_using_config_map_only: true
    local_mode: false
    max_retries: 0
    no_verify_ssl: false
    num_workers: 0
    prefer_full_pod_name: true
    proxy_address: ""
    region: "us-east-1"
    request_timeout_seconds: 0
    resource_arn: ""
    role_arn: ""
    profile: ""
    shared_credentials_file: [ ]
  tcplog/emf_logs:
    attributes: {}
    encoding: utf-8
    id: tcp_input
    listen_address: 0.0.0.0:25888
    operators: []
    output: []
    resource: {}
    retry_on_failure:
      enabled: false
      initial_interval: 0s
      max_elapsed_time: 0s
      max_interval: 0s
    storage: null
    type: tcp_input
  udplog/emf_logs:
    attributes: {}
    encoding: utf-8
    id: udp_input
    listen_address: 0.0.0.0:25888
    multiline:
      line_end_pattern: .^
      line_start_pattern: ""
    operators: []
    output: []
    resource: {}
    retry_on_failure:
      enabled: false
      initial_interval: 0s
      max_elapsed_time: 0s
      max_interval: 0s
    storage: null
    type: udp_input
service:
  extensions: []
  pipelines:
    logs/emf_logs:
      exporters:
        - awscloudwatchlogs/emf_logs
      processors:
        - batch/emf_logs
      receivers:
        - tcplog/emf_logs
        - udplog/emf_logs
    metrics/containerinsights:
      exporters:
        - awsemf/containerinsights
      processors:
        - metricstransform/containerinsights
        - batch/containerinsights
      receivers:
        - awscontainerinsightreceiver
  telemetry:
    logs:
      development: false
      disable_caller: false
      disable_stacktrace: false
      encoding: console
      error_output_paths: []
      initial_fields: {}
      level: info
      output_paths: []
      sampling:
        initial: 2
        thereafter: 500
    metrics:
      address: ""
      level: None
      readers: []
    resource: {}
    traces:
      processors: []
      propagators: []
